# Generated by Django 3.2.1 on 2023-07-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_reason_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="reason",
            name="order",
            field=models.IntegerField(default=0, verbose_name="orden"),
        ),
    ]
